### ISSUE TITLE
The provided links in Getting Started don't work for Mac

### ISSUE THREAD

**Issue by NightMachinery** [typelead/etlas#35]
I have downloaded https://cdnverify.eta-lang.org/eta-binaries//etlas-1.2.0.0/binaries/x86_64-osx/etlas 3 times, and the result has been the same: the dmg file is unreadable.
I have tried downloading with Safari, Chrome, and Progressive Downloader. Safari saves it as *.dms, the other two extension-less.

**Comment by rahulmutt** [comment]
@NightMachinary The file you downloaded is a raw binary and not a dmg file. The instructions say to add it to your path so you can use it from the command line. Let us know if the instructions were confusing and we need to word it better.

**Comment by NightMachinery** [comment]
Oh! Thanks!
Change this on the getting started guide then:
"On Safari the extension of the etlas binary is dms instead of dmg. So please avoid downloading on Safari."

It implies it is a .dmg.
