### ISSUE TITLE
"etlas select" lists eta-0.0.6.6 but cannot select it

### ISSUE THREAD

**Issue by y-taka-23** [typelead/etlas#36]
```console
$ etlas update
Downloading the latest package lists from:
- hackage.haskell.org
- etlas.org
Updating binary package index.
To revert to previous state run:
    etlas update --index-state='2018-02-28T04:28:32Z'
Updating the eta-hackage patch set.

$ etlas --version
etlas version 1.2.0.0
compiled using version 2.1.0.0 of the etlas-cabal library

$ etlas select --list
0.0.6.6
0.0.9.1
0.0.9.2
0.0.9.3
0.0.9.4
0.0.9.5
0.0.9.6
0.7.0.1
0.7.0.2

$ etlas select 0.0.6.6
etlas: Unable to find eta-0.0.6.6 in any of your configured binary indices.

Run `etlas update` and try again.
If that doesn't work, please report this as a bug at

https://github.com/typelead/eta/issues/new

specifying your Etlas version.
```

The other versions >=0.0.9.1 are okay.

**Comment by rahulmutt** [comment]
@y-taka-23 Thank you so much for reporting this! I checked the layout on the binary server and it looks like it only has binaries for OS X for some reason for `0.0.6.6` in particular. Anyways, `0.0.6.6` is super old and buggy so it's probably better just deleting it. I'll update the index file so that `0.0.6.6` doesn't show up.

**Comment by jneira** [comment]
@rahulmutt i've just check this and i am having this old version in my `etlas select --list`, is there still in index or i have to clean some cache file?

**Comment by rahulmutt** [comment]
It's still in the index it looks like - haven't had time to change it. Most of that infrastructure is automated now and I don't want to mess with manual overrides. For now, we'll leave it as it is unless someone really wants to use `0.0.6.6` for some reason.
