### ISSUE TITLE
error installing hpack

### ISSUE THREAD

**Issue by amilkov3** [typelead/etlas#38]
Several packages fail to install via `etlas install hpack`:

```
etlas: Error: some packages failed to install:
Cabal-2.0.1.1-JF7SBTn9Y7vKthtVqM5Cel depends on Cabal-2.0.1.1 which failed to
install.
hpack-0.25.0-2iN83w07o4UEz86J7mimhV depends on hpack-0.25.0 which failed to
install.
unix-2.7.2.2-EjsyPnKNuFmAYXDUkSFrP5 failed during the building phase. The
exception was:
ExitFailure 1
```

my etlas version is `1.2.0.0`

**Comment by rahulmutt** [comment]
`hpack` depends on `yaml` package which has yet to be ported (https://github.com/typelead/eta/issues/607).

Moreover, we'll need to patch the `Cabal` library to remove the platform-specific stuff.

**Comment by amilkov3** [comment]
ah ok gotcha. yea im just installing these through stack for now (needed `hpack` to build the `intellij-eta` project) so feel free to close this, unless there isn't already a todo ticket for porting `Cabal`

**Comment by rahulmutt** [comment]
Filed an issue here: https://github.com/typelead/eta-hackage/issues/76

Closing now.
