### ISSUE TITLE
While installing etlas with stack getting an error 

### ISSUE THREAD

**Issue by shubhamkumar13** [typelead/etlas#44]
``getDirectoryContents:openDirStream: does not exist (No such file or directory)``

**Comment by shubhamkumar13** [comment]
``stack install etlas
/home/shubham/etlas/hackage-security/hackage-security/: getDirectoryContents:openDirStream: does not exist (No such file or directory)

**Comment by rahulmutt** [comment]
@shubhamkumar13 It should be fixed by running the following where you cloned the `eta` repository:
```
git submodule sync
git submodule update --init --recursive
```

**Comment by shubhamkumar13** [comment]
thanks
