### ISSUE TITLE
Add a #define for CPP

### ISSUE THREAD

**Issue by puffnfresh** [typelead/etlas#60]
We already have `__GLASGOW_HASKELL__` defined. It'd be good to have something for Eta as well, so that we can upstream Eta's patches.

**Comment by Jyothsnasrinivas** [comment]
@puffnfresh We already have a constant `ETA_VERSION`. We are also planning on sending upstream PRs pretty soon. We are currently in the process of doing extensive testing and fixing all the bugs that come up.

**Comment by puffnfresh** [comment]
That's perfect. Thanks!
